ln -s ~/dotfiles/.bashrc ~/.bashrc
ln -s ~/dotfiles/.dircolors ~/.dircolors
ln -s ~/dotfiles/.bash_prompt.sh ~/.bash_prompt.sh
ln -s ~/dotfiles/.xmonad ~/
ln -s ~/dotfiles/.xmobarrc ~/
ln -s ~/dotfiles/.gitconfig ~/
ln -s ~/dotfiles/.pam_environment ~/
ln -s ~/dotfiles/.pythonrc ~/
ln -s ~/dotfiles/.bash_profile ~/
